apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment
      env: blue  
  template:
    metadata:
      labels:
        app: payment
        env: blue  # Blue environment label
    spec:
      containers:
      - name: payment-service
        image: njl010docker/payment:latest  # Blue version
        ports:
        - containerPort: 3000
