apiVersion: v1
kind: Service
metadata:
  name: payment-svc-green
spec:
  selector:
    app: payment
    env: green  # Traffic for the Green environment
  ports:
    - protocol: TCP
      port: 80         # Port inside the cluster
      targetPort: 3000  # Port the app is listening on inside the pod
      nodePort: 30001   # Exposed external port
  type: NodePort

