apiVersion: v1
kind: Service
metadata:
  name: payment-svc
spec:
  selector:
    app: payment-svc
  ports:
    - protocol: TCP
      port: 3000         # Port inside the cluster
      targetPort: 3000    # Port the app is listening on
      nodePort: 30000   # Exposed external port
  type: NodePort
